name: Update IP Ranges

on:
  schedule:
    - cron: '0 0 * * 0' # Run weekly at midnight on Sunday
  workflow_dispatch: # Allow manual triggering

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23'

      - name: Run CLI to generate Go file
        run: |
          go run ranges/main.go -format go -output ranges/generated.go

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add ranges/generated.go
          git commit -m "Automated update of IP ranges"
          git push
